version = 1

# -------------------------
# Python analyzer
# -------------------------
[[analyzers]]
name = "python"
enabled = true
version = "3.11"
dependency_file_paths = ["requirements.txt", "requirements-docs.txt"]

# -------------------------
# JavaScript analyzer for Node.js scripts
# -------------------------
[[analyzers]]
name = "javascript"
enabled = true
version = "es2022"
[analyzers.meta]
environment = ["nodejs", "vitest"]
include_patterns = [
    "merge-assets.js",
    "copy-html.js",
    ".eleventy.js",
    "packages/**/*.js"
]
exclude_patterns = ["**/node_modules/", "_site/", "_deploy/"]

# -------------------------
# JavaScript analyzer for browser
# -------------------------
[[analyzers]]
name = "javascript"
enabled = true
version = "es2022"
[analyzers.meta]
environment = ["browser"]
include_patterns = ["frontend/**/*.js"]
exclude_patterns = ["**/node_modules/", "_site/", "_deploy/"]

# -------------------------
# Secrets, Shell, Docker
# -------------------------
[[analyzers]]
name = "secrets"
enabled = true

[[analyzers]]
name = "shell"
enabled = true

[[analyzers]]
name = "docker"
enabled = true

# -------------------------
# Transformers
# -------------------------
[[transformers]]
name = "isort"
enabled = true

[[transformers]]
name = "black"
enabled = true

[[transformers]]
name = "prettier"
enabled = true
