name: Build and Deploy Eleventy site

on:
  push:
    branches:
      - main
      - max-updates-check-ghpages

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          path: .

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build Eleventy site
        run: npm run build

      - name: Current directory path
        run: pwd

      - name: List root directory
        run: ls -la

      - name: List _site directory (if exists)
        run: ls -la _site || echo "_site not found"

      - name: _site directory path
        run: cd _site && pwd

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site/
